# Generated by Django 3.1.2 on 2020-11-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201106_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='../images/cover/default-cover-img.gif', upload_to=''),
        ),
    ]
