# Generated by Django 3.1.2 on 2020-11-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201109_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='default-cover-img.gif', upload_to='cover'),
        ),
    ]
